[package]
name = "prometheus_alert_overrider"
version = "0.1.0"
authors = ["Brandon Kauffman <bkauffman7@liberty.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4"
regex = "1"
structopt = "0.3"